KNOWLEDGE_CHUNKS = [
    {
        "title": "PTA mobile device and complaint guidance",
        "source_name": "Pakistan Telecommunication Authority",
        "source_type": "federal_regulator",
        "source_url": "https://www.pta.gov.pk/",
        "issuing_authority": "Pakistan Telecommunication Authority",
        "jurisdiction": "Pakistan",
        "province": None,
        "city": None,
        "category": "lost_or_stolen_vehicle_device",
        "subcategory": "lost_phone",
        "content": "General Pakistan-level telecom guidance source for PTA/DIRBS/mobile device and complaint-management verification. Users should verify current blocking or complaint steps directly with PTA and telecom operators.",
        "summary": "Use PTA/telecom guidance for phone IMEI/SIM-related steps after police reporting where relevant.",
        "language": "english",
        "verified_at": "2026-06-14",
        "last_checked_at": "2026-06-14",
        "confidence_level": "official_source_metadata",
    },
    {
        "title": "Police loss/theft report guidance",
        "source_name": "Islamabad Capital Police",
        "source_type": "police",
        "source_url": "https://islamabadpolice.gov.pk/",
        "issuing_authority": "Islamabad Capital Police",
        "jurisdiction": "Islamabad",
        "province": "Islamabad Capital Territory",
        "city": "Islamabad",
        "category": "lost_or_stolen_vehicle_device",
        "subcategory": "stolen_phone",
        "content": "Official police source metadata for reporting loss/theft matters in Islamabad. Exact requirements can vary by report type and should be verified with the receiving police office.",
        "summary": "Police reporting source for lost/stolen devices and vehicles in Islamabad.",
        "language": "english",
        "verified_at": "2026-06-14",
        "last_checked_at": "2026-06-14",
        "confidence_level": "official_source_metadata",
    },
    {
        "title": "Police Khidmat Markaz loss-report services",
        "source_name": "Police Khidmat Markaz Punjab",
        "source_type": "public_service_portal",
        "source_url": "https://pkm.punjab.gov.pk/",
        "issuing_authority": "Punjab Police",
        "jurisdiction": "Punjab",
        "province": "Punjab",
        "city": None,
        "category": "lost_or_stolen_vehicle_device",
        "subcategory": "stolen_bike",
        "content": "Official Punjab Police service portal metadata for citizen services such as loss-reporting. Exact service requirements should be verified on the official portal or service center.",
        "summary": "Punjab public-service reporting source for loss reports and police service-center guidance.",
        "language": "english",
        "verified_at": "2026-06-14",
        "last_checked_at": "2026-06-14",
        "confidence_level": "official_source_metadata",
    },
    {
        "title": "NEPRA consumer complaint guidance",
        "source_name": "National Electric Power Regulatory Authority",
        "source_type": "federal_regulator",
        "source_url": "https://nepra.org.pk/",
        "issuing_authority": "NEPRA",
        "jurisdiction": "Pakistan",
        "province": None,
        "city": None,
        "category": "utility_bill_overcharging",
        "subcategory": "electricity_bill_overcharging",
        "content": "Official regulator source metadata for electricity consumer complaints. Users should first collect bill reference details, meter proof, provider complaint reference, and verify escalation requirements directly with NEPRA.",
        "summary": "NEPRA is the federal regulator source for electricity consumer complaint escalation verification.",
        "language": "english",
        "verified_at": "2026-06-14",
        "last_checked_at": "2026-06-14",
        "confidence_level": "official_source_metadata",
    },
    {
        "title": "OGRA complaint guidance",
        "source_name": "Oil and Gas Regulatory Authority",
        "source_type": "federal_regulator",
        "source_url": "https://ogra.org.pk/",
        "issuing_authority": "OGRA",
        "jurisdiction": "Pakistan",
        "province": None,
        "city": None,
        "category": "utility_bill_overcharging",
        "subcategory": "gas_bill_overcharging",
        "content": "Official regulator source metadata for gas utility complaint escalation. Users should verify current OGRA complaint requirements and first collect provider complaint/reference details.",
        "summary": "OGRA is the Pakistan-level regulator source for gas complaint escalation verification.",
        "language": "english",
        "verified_at": "2026-06-14",
        "last_checked_at": "2026-06-14",
        "confidence_level": "official_source_metadata",
    },
    {
        "title": "K-Electric consumer complaint procedure",
        "source_name": "K-Electric",
        "source_type": "utility_provider",
        "source_url": "https://www.ke.com.pk/customer-services/complaint/",
        "provider": "K-Electric",
        "issuing_authority": "K-Electric",
        "jurisdiction": "Karachi/service areas",
        "province": "Sindh",
        "city": None,
        "category": "utility_bill_overcharging",
        "subcategory": "electricity_bill_overcharging",
        "content": "K-Electric is the electricity provider for Karachi and surrounding areas. For bill overcharging complaints, file first at a K-Electric service center or via their 118 helpline. Escalate unresolved cases to NEPRA.",
        "summary": "K-Electric is the provider-level complaint source for Karachi electricity billing.",
        "language": "english",
        "verified_at": "2026-06-14",
        "last_checked_at": "2026-06-14",
        "confidence_level": "official_source_metadata",
    },
    {
        "title": "LESCO consumer complaint procedure",
        "source_name": "Lahore Electric Supply Company (LESCO)",
        "source_type": "utility_provider",
        "source_url": "https://www.lesco.gov.pk/",
        "provider": "LESCO",
        "issuing_authority": "LESCO",
        "jurisdiction": "Lahore/service areas",
        "province": "Punjab",
        "city": None,
        "category": "utility_bill_overcharging",
        "subcategory": "electricity_bill_overcharging",
        "content": "LESCO provides electricity in Lahore and surrounding areas. File billing complaints at a LESCO service center or via their helpline. Escalate to NEPRA if unresolved.",
        "summary": "LESCO is the provider-level complaint source for Lahore electricity billing.",
        "language": "english",
        "verified_at": "2026-06-14",
        "last_checked_at": "2026-06-14",
        "confidence_level": "official_source_metadata",
    },
    {
        "title": "IESCO consumer complaint procedure",
        "source_name": "Islamabad Electric Supply Company (IESCO)",
        "source_type": "utility_provider",
        "source_url": "https://www.iesco.com.pk/",
        "provider": "IESCO",
        "issuing_authority": "IESCO",
        "jurisdiction": "Islamabad/Rawalpindi/service areas",
        "province": "Punjab/ICT",
        "city": None,
        "category": "utility_bill_overcharging",
        "subcategory": "electricity_bill_overcharging",
        "content": "IESCO provides electricity in Islamabad, Rawalpindi and surrounding areas. File billing complaints at an IESCO service center or via their helpline. Escalate to NEPRA if unresolved.",
        "summary": "IESCO is the provider-level complaint source for Islamabad/Rawalpindi electricity billing.",
        "language": "english",
        "verified_at": "2026-06-14",
        "last_checked_at": "2026-06-14",
        "confidence_level": "official_source_metadata",
    },
    {
        "title": "FESCO consumer complaint procedure",
        "source_name": "Faisalabad Electric Supply Company (FESCO)",
        "source_type": "utility_provider",
        "source_url": "https://www.fesco.com.pk/",
        "provider": "FESCO",
        "issuing_authority": "FESCO",
        "jurisdiction": "Faisalabad/service areas",
        "province": "Punjab",
        "city": None,
        "category": "utility_bill_overcharging",
        "subcategory": "electricity_bill_overcharging",
        "content": "FESCO provides electricity in Faisalabad and surrounding areas. File billing complaints at a FESCO service center or helpline. Escalate to NEPRA if unresolved.",
        "summary": "FESCO is the provider-level complaint source for Faisalabad electricity billing.",
        "language": "english",
        "verified_at": "2026-06-14",
        "last_checked_at": "2026-06-14",
        "confidence_level": "official_source_metadata",
    },
    {
        "title": "SNGPL consumer complaint procedure",
        "source_name": "Sui Northern Gas Pipelines Limited (SNGPL)",
        "source_type": "utility_provider",
        "source_url": "https://www.sngpl.com.pk/",
        "provider": "SNGPL",
        "issuing_authority": "SNGPL",
        "jurisdiction": "Punjab/KP/service areas",
        "province": "Punjab",
        "city": None,
        "category": "utility_bill_overcharging",
        "subcategory": "gas_bill_overcharging",
        "content": "SNGPL supplies gas in Punjab and KP. File billing complaints at an SNGPL service center or via their helpline. Escalate to OGRA if unresolved.",
        "summary": "SNGPL is the provider-level complaint source for Punjab/KP gas billing.",
        "language": "english",
        "verified_at": "2026-06-14",
        "last_checked_at": "2026-06-14",
        "confidence_level": "official_source_metadata",
    },
    {
        "title": "SSGC consumer complaint procedure",
        "source_name": "Sui Southern Gas Company (SSGC)",
        "source_type": "utility_provider",
        "source_url": "https://www.ssgc.com.pk/",
        "provider": "SSGC",
        "issuing_authority": "SSGC",
        "jurisdiction": "Sindh/Balochistan/service areas",
        "province": "Sindh",
        "city": None,
        "category": "utility_bill_overcharging",
        "subcategory": "gas_bill_overcharging",
        "content": "SSGC supplies gas in Sindh and Balochistan. File billing complaints at an SSGC service center or via their helpline. Escalate to OGRA if unresolved.",
        "summary": "SSGC is the provider-level complaint source for Sindh/Balochistan gas billing.",
        "language": "english",
        "verified_at": "2026-06-14",
        "last_checked_at": "2026-06-14",
        "confidence_level": "official_source_metadata",
    },
    {
        "title": "WASA Lahore water complaint procedure",
        "source_name": "Water and Sanitation Agency Lahore (WASA)",
        "source_type": "utility_provider",
        "source_url": "https://wasa.punjab.gov.pk/",
        "provider": "WASA",
        "issuing_authority": "WASA Lahore",
        "jurisdiction": "Lahore",
        "province": "Punjab",
        "city": "Lahore",
        "category": "utility_bill_overcharging",
        "subcategory": "water_bill_overcharging",
        "content": "WASA Lahore handles water billing complaints for Lahore. File a complaint at a WASA service center or their helpline. Escalate to Punjab Local Government if unresolved.",
        "summary": "WASA Lahore is the provider-level complaint source for Lahore water billing.",
        "language": "english",
        "verified_at": "2026-06-14",
        "last_checked_at": "2026-06-14",
        "confidence_level": "official_source_metadata",
    },
    {
        "title": "KW&SB Karachi water complaint procedure",
        "source_name": "Karachi Water and Sewerage Board (KW&SB)",
        "source_type": "utility_provider",
        "source_url": "https://www.kwsb.org.pk/",
        "provider": "KW&SB",
        "issuing_authority": "KW&SB",
        "jurisdiction": "Karachi",
        "province": "Sindh",
        "city": "Karachi",
        "category": "utility_bill_overcharging",
        "subcategory": "water_bill_overcharging",
        "content": "KW&SB handles water billing complaints for Karachi. File a complaint at a KW&SB office or their helpline. Escalate to Sindh Local Government if unresolved.",
        "summary": "KW&SB is the provider-level complaint source for Karachi water billing.",
        "language": "english",
        "verified_at": "2026-06-14",
        "last_checked_at": "2026-06-14",
        "confidence_level": "official_source_metadata",
    },
    {
        "title": "FOSPAH workplace harassment complaint guidance",
        "source_name": "Federal Ombudsperson Secretariat for Protection Against Harassment",
        "source_type": "federal_ombudsperson",
        "source_url": "https://www.fospah.gov.pk/",
        "issuing_authority": "FOSPAH",
        "jurisdiction": "Pakistan",
        "province": None,
        "city": None,
        "category": "workplace_harassment_women",
        "subcategory": "workplace_harassment_women",
        "content": "Official federal ombudsperson source metadata for workplace harassment guidance. Users should verify complaint procedure, jurisdiction, confidentiality, and current forms directly with FOSPAH or a relevant provincial authority.",
        "summary": "FOSPAH is an official Pakistan-level source for workplace harassment complaint procedure verification.",
        "language": "english",
        "verified_at": "2026-06-14",
        "last_checked_at": "2026-06-14",
        "confidence_level": "official_source_metadata",
    },
]
