KNOWLEDGE_CHUNKS = [
    {
        "title": "PTA mobile device and complaint guidance",
        "source_name": "Pakistan Telecommunication Authority",
        "source_type": "federal_regulator",
        "source_url": "https://www.pta.gov.pk/",
        "issuing_authority": "Pakistan Telecommunication Authority",
        "jurisdiction": "Pakistan",
        "province": None,
        "city": None,
        "category": "lost_or_stolen_vehicle_device",
        "subcategory": "lost_phone",
        "content": "General Pakistan-level telecom guidance source for PTA/DIRBS/mobile device and complaint-management verification. Users should verify current blocking or complaint steps directly with PTA and telecom operators.",
        "summary": "Use PTA/telecom guidance for phone IMEI/SIM-related steps after police reporting where relevant.",
        "language": "english",
        "verified_at": "2026-06-14",
        "last_checked_at": "2026-06-14",
        "confidence_level": "official_source_metadata",
    },
    {
        "title": "Police loss/theft report guidance",
        "source_name": "Islamabad Capital Police",
        "source_type": "police",
        "source_url": "https://islamabadpolice.gov.pk/",
        "issuing_authority": "Islamabad Capital Police",
        "jurisdiction": "Islamabad",
        "province": "Islamabad Capital Territory",
        "city": "Islamabad",
        "category": "lost_or_stolen_vehicle_device",
        "subcategory": "stolen_phone",
        "content": "Official police source metadata for reporting loss/theft matters in Islamabad. Exact requirements can vary by report type and should be verified with the receiving police office.",
        "summary": "Police reporting source for lost/stolen devices and vehicles in Islamabad.",
        "language": "english",
        "verified_at": "2026-06-14",
        "last_checked_at": "2026-06-14",
        "confidence_level": "official_source_metadata",
    },
    {
        "title": "Police Khidmat Markaz loss-report services",
        "source_name": "Police Khidmat Markaz Punjab",
        "source_type": "public_service_portal",
        "source_url": "https://pkm.punjab.gov.pk/",
        "issuing_authority": "Punjab Police",
        "jurisdiction": "Punjab",
        "province": "Punjab",
        "city": None,
        "category": "lost_or_stolen_vehicle_device",
        "subcategory": "stolen_bike",
        "content": "Official Punjab Police service portal metadata for citizen services such as loss-reporting. Exact service requirements should be verified on the official portal or service center.",
        "summary": "Punjab public-service reporting source for loss reports and police service-center guidance.",
        "language": "english",
        "verified_at": "2026-06-14",
        "last_checked_at": "2026-06-14",
        "confidence_level": "official_source_metadata",
    },
    {
        "title": "NEPRA consumer complaint guidance",
        "source_name": "National Electric Power Regulatory Authority",
        "source_type": "federal_regulator",
        "source_url": "https://nepra.org.pk/",
        "issuing_authority": "NEPRA",
        "jurisdiction": "Pakistan",
        "province": None,
        "city": None,
        "category": "utility_bill_overcharging",
        "subcategory": "electricity_bill_overcharging",
        "content": "Official regulator source metadata for electricity consumer complaints. Users should first collect bill reference details, meter proof, provider complaint reference, and verify escalation requirements directly with NEPRA.",
        "summary": "NEPRA is the federal regulator source for electricity consumer complaint escalation verification.",
        "language": "english",
        "verified_at": "2026-06-14",
        "last_checked_at": "2026-06-14",
        "confidence_level": "official_source_metadata",
    },
    {
        "title": "OGRA complaint guidance",
        "source_name": "Oil and Gas Regulatory Authority",
        "source_type": "federal_regulator",
        "source_url": "https://ogra.org.pk/",
        "issuing_authority": "OGRA",
        "jurisdiction": "Pakistan",
        "province": None,
        "city": None,
        "category": "utility_bill_overcharging",
        "subcategory": "gas_bill_overcharging",
        "content": "Official regulator source metadata for gas utility complaint escalation. Users should verify current OGRA complaint requirements and first collect provider complaint/reference details.",
        "summary": "OGRA is the Pakistan-level regulator source for gas complaint escalation verification.",
        "language": "english",
        "verified_at": "2026-06-14",
        "last_checked_at": "2026-06-14",
        "confidence_level": "official_source_metadata",
    },
    {
        "title": "FOSPAH workplace harassment complaint guidance",
        "source_name": "Federal Ombudsperson Secretariat for Protection Against Harassment",
        "source_type": "federal_ombudsperson",
        "source_url": "https://www.fospah.gov.pk/",
        "issuing_authority": "FOSPAH",
        "jurisdiction": "Pakistan",
        "province": None,
        "city": None,
        "category": "workplace_harassment_women",
        "subcategory": "workplace_harassment_women",
        "content": "Official federal ombudsperson source metadata for workplace harassment guidance. Users should verify complaint procedure, jurisdiction, confidentiality, and current forms directly with FOSPAH or a relevant provincial authority.",
        "summary": "FOSPAH is an official Pakistan-level source for workplace harassment complaint procedure verification.",
        "language": "english",
        "verified_at": "2026-06-14",
        "last_checked_at": "2026-06-14",
        "confidence_level": "official_source_metadata",
    },
]
