VERIFIED_SOURCES = [
    # ── LOST / STOLEN PHONE / BIKE / CAR ────────────────────────────────────
    {
        "id": "pta",
        "title": "PTA mobile device and DIRBS guidance",
        "source_name": "Pakistan Telecommunication Authority (PTA)",
        "source_type": "federal_regulator",
        "source_url": "https://www.pta.gov.pk/",
        "category": "lost_or_stolen_vehicle_device",
        "subcategory": None,
        "provider": None,
        "jurisdiction": "Pakistan",
        "province": None,
        "city": None,
        "verified_at": "2026-06-14",
        "confidence_level": "official_source_metadata",
    },
    {
        "id": "islamabad_police",
        "title": "Islamabad Capital Territory Police",
        "source_name": "Islamabad Capital Territory Police",
        "source_type": "police",
        "source_url": "https://islamabadpolice.gov.pk/",
        "category": "lost_or_stolen_vehicle_device",
        "subcategory": None,
        "provider": None,
        "jurisdiction": "Islamabad",
        "province": "Islamabad Capital Territory",
        "city": "Islamabad",
        "verified_at": "2026-06-14",
        "confidence_level": "official_source_metadata",
    },
    {
        "id": "punjab_police",
        "title": "Punjab Police",
        "source_name": "Punjab Police",
        "source_type": "police",
        "source_url": "https://punjabpolice.gov.pk/",
        "category": "lost_or_stolen_vehicle_device",
        "subcategory": None,
        "provider": None,
        "jurisdiction": "Punjab",
        "province": "Punjab",
        "city": None,
        "verified_at": "2026-06-14",
        "confidence_level": "official_source_metadata",
    },
    {
        "id": "pkm_punjab",
        "title": "Police Khidmat Markaz Punjab (loss-report portal)",
        "source_name": "Police Khidmat Markaz Punjab",
        "source_type": "public_service_portal",
        "source_url": "https://pkm.punjab.gov.pk/",
        "category": "lost_or_stolen_vehicle_device",
        "subcategory": None,
        "provider": None,
        "jurisdiction": "Punjab",
        "province": "Punjab",
        "city": None,
        "verified_at": "2026-06-14",
        "confidence_level": "official_source_metadata",
    },
    {
        "id": "sindh_police",
        "title": "Sindh Police",
        "source_name": "Sindh Police",
        "source_type": "police",
        "source_url": "https://sindhpolice.gov.pk/",
        "category": "lost_or_stolen_vehicle_device",
        "subcategory": None,
        "provider": None,
        "jurisdiction": "Sindh",
        "province": "Sindh",
        "city": None,
        "verified_at": "2026-06-14",
        "confidence_level": "official_source_metadata",
    },
    {
        "id": "cplc",
        "title": "Citizen Police Liaison Committee (Karachi/Sindh)",
        "source_name": "Citizen Police Liaison Committee (CPLC)",
        "source_type": "public_safety_service",
        "source_url": "https://www.cplc.org.pk/",
        "category": "lost_or_stolen_vehicle_device",
        "subcategory": None,
        "provider": None,
        "jurisdiction": "Karachi/Sindh",
        "province": "Sindh",
        "city": "Karachi",
        "verified_at": "2026-06-14",
        "confidence_level": "official_source_metadata",
    },
    {
        "id": "kpk_police",
        "title": "Khyber Pakhtunkhwa Police",
        "source_name": "Khyber Pakhtunkhwa Police",
        "source_type": "police",
        "source_url": "https://kppolice.gov.pk/",
        "category": "lost_or_stolen_vehicle_device",
        "subcategory": None,
        "provider": None,
        "jurisdiction": "Khyber Pakhtunkhwa",
        "province": "Khyber Pakhtunkhwa",
        "city": None,
        "verified_at": "2026-06-14",
        "confidence_level": "official_source_metadata",
    },
    {
        "id": "balochistan_police",
        "title": "Balochistan Police",
        "source_name": "Balochistan Police",
        "source_type": "police",
        "source_url": "https://balochistanpolice.gov.pk/",
        "category": "lost_or_stolen_vehicle_device",
        "subcategory": None,
        "provider": None,
        "jurisdiction": "Balochistan",
        "province": "Balochistan",
        "city": None,
        "verified_at": "2026-06-14",
        "confidence_level": "official_source_metadata",
    },
    # ── ELECTRICITY BILL OVERCHARGING ────────────────────────────────────────
    {
        "id": "nepra",
        "title": "NEPRA consumer complaint guidance",
        "source_name": "National Electric Power Regulatory Authority (NEPRA)",
        "source_type": "federal_regulator",
        "source_url": "https://nepra.org.pk/",
        "category": "utility_bill_overcharging",
        "subcategory": "electricity_bill_overcharging",
        "provider": None,
        "jurisdiction": "Pakistan",
        "province": None,
        "city": None,
        "verified_at": "2026-06-14",
        "confidence_level": "official_source_metadata",
    },
    {
        "id": "ke",
        "title": "K-Electric consumer complaint",
        "source_name": "K-Electric",
        "source_type": "utility_provider",
        "source_url": "https://www.ke.com.pk/",
        "category": "utility_bill_overcharging",
        "subcategory": "electricity_bill_overcharging",
        "provider": "K-Electric",
        "jurisdiction": "Karachi/service areas",
        "province": "Sindh",
        "city": None,
        "verified_at": "2026-06-14",
        "confidence_level": "official_source_metadata",
    },
    {
        "id": "lesco",
        "title": "LESCO consumer complaint",
        "source_name": "Lahore Electric Supply Company (LESCO)",
        "source_type": "utility_provider",
        "source_url": "https://www.lesco.gov.pk/",
        "category": "utility_bill_overcharging",
        "subcategory": "electricity_bill_overcharging",
        "provider": "LESCO",
        "jurisdiction": "Lahore/service areas",
        "province": "Punjab",
        "city": None,
        "verified_at": "2026-06-14",
        "confidence_level": "official_source_metadata",
    },
    {
        "id": "iesco",
        "title": "IESCO consumer complaint",
        "source_name": "Islamabad Electric Supply Company (IESCO)",
        "source_type": "utility_provider",
        "source_url": "https://www.iesco.com.pk/",
        "category": "utility_bill_overcharging",
        "subcategory": "electricity_bill_overcharging",
        "provider": "IESCO",
        "jurisdiction": "Islamabad/Rawalpindi/service areas",
        "province": "Punjab/ICT",
        "city": None,
        "verified_at": "2026-06-14",
        "confidence_level": "official_source_metadata",
    },
    {
        "id": "fesco",
        "title": "FESCO consumer complaint",
        "source_name": "Faisalabad Electric Supply Company (FESCO)",
        "source_type": "utility_provider",
        "source_url": "https://www.fesco.com.pk/",
        "category": "utility_bill_overcharging",
        "subcategory": "electricity_bill_overcharging",
        "provider": "FESCO",
        "jurisdiction": "Faisalabad/service areas",
        "province": "Punjab",
        "city": None,
        "verified_at": "2026-06-14",
        "confidence_level": "official_source_metadata",
    },
    {
        "id": "mepco",
        "title": "MEPCO consumer complaint",
        "source_name": "Multan Electric Power Company (MEPCO)",
        "source_type": "utility_provider",
        "source_url": "https://mepco.com.pk/",
        "category": "utility_bill_overcharging",
        "subcategory": "electricity_bill_overcharging",
        "provider": "MEPCO",
        "jurisdiction": "Multan/South Punjab/service areas",
        "province": "Punjab",
        "city": None,
        "verified_at": "2026-06-14",
        "confidence_level": "official_source_metadata",
    },
    {
        "id": "gepco",
        "title": "GEPCO consumer complaint",
        "source_name": "Gujranwala Electric Power Company (GEPCO)",
        "source_type": "utility_provider",
        "source_url": "https://gepco.com.pk/",
        "category": "utility_bill_overcharging",
        "subcategory": "electricity_bill_overcharging",
        "provider": "GEPCO",
        "jurisdiction": "Gujranwala/service areas",
        "province": "Punjab",
        "city": None,
        "verified_at": "2026-06-14",
        "confidence_level": "official_source_metadata",
    },
    {
        "id": "hesco",
        "title": "HESCO consumer complaint",
        "source_name": "Hyderabad Electric Supply Company (HESCO)",
        "source_type": "utility_provider",
        "source_url": "https://www.hesco.gov.pk/",
        "category": "utility_bill_overcharging",
        "subcategory": "electricity_bill_overcharging",
        "provider": "HESCO",
        "jurisdiction": "Hyderabad/Sindh service areas",
        "province": "Sindh",
        "city": None,
        "verified_at": "2026-06-14",
        "confidence_level": "official_source_metadata",
    },
    {
        "id": "sepco",
        "title": "SEPCO consumer complaint",
        "source_name": "Sukkur Electric Power Company (SEPCO)",
        "source_type": "utility_provider",
        "source_url": "https://sepco.com.pk/",
        "category": "utility_bill_overcharging",
        "subcategory": "electricity_bill_overcharging",
        "provider": "SEPCO",
        "jurisdiction": "Sukkur/North Sindh service areas",
        "province": "Sindh",
        "city": None,
        "verified_at": "2026-06-14",
        "confidence_level": "official_source_metadata",
    },
    {
        "id": "pesco",
        "title": "PESCO consumer complaint",
        "source_name": "Peshawar Electric Supply Company (PESCO)",
        "source_type": "utility_provider",
        "source_url": "https://pesco.gov.pk/",
        "category": "utility_bill_overcharging",
        "subcategory": "electricity_bill_overcharging",
        "provider": "PESCO",
        "jurisdiction": "Peshawar/KP service areas",
        "province": "Khyber Pakhtunkhwa",
        "city": None,
        "verified_at": "2026-06-14",
        "confidence_level": "official_source_metadata",
    },
    {
        "id": "qesco",
        "title": "QESCO consumer complaint",
        "source_name": "Quetta Electric Supply Company (QESCO)",
        "source_type": "utility_provider",
        "source_url": "https://qesco.com.pk/",
        "category": "utility_bill_overcharging",
        "subcategory": "electricity_bill_overcharging",
        "provider": "QESCO",
        "jurisdiction": "Quetta/Balochistan service areas",
        "province": "Balochistan",
        "city": None,
        "verified_at": "2026-06-14",
        "confidence_level": "official_source_metadata",
    },
    # ── GAS BILL OVERCHARGING ────────────────────────────────────────────────
    {
        "id": "ogra",
        "title": "OGRA consumer complaint guidance",
        "source_name": "Oil and Gas Regulatory Authority (OGRA)",
        "source_type": "federal_regulator",
        "source_url": "https://ogra.org.pk/",
        "category": "utility_bill_overcharging",
        "subcategory": "gas_bill_overcharging",
        "provider": None,
        "jurisdiction": "Pakistan",
        "province": None,
        "city": None,
        "verified_at": "2026-06-14",
        "confidence_level": "official_source_metadata",
    },
    {
        "id": "sngpl",
        "title": "SNGPL consumer complaint",
        "source_name": "Sui Northern Gas Pipelines Limited (SNGPL)",
        "source_type": "utility_provider",
        "source_url": "https://www.sngpl.com.pk/",
        "category": "utility_bill_overcharging",
        "subcategory": "gas_bill_overcharging",
        "provider": "SNGPL",
        "jurisdiction": "Punjab/KP/service areas",
        "province": "Punjab",
        "city": None,
        "verified_at": "2026-06-14",
        "confidence_level": "official_source_metadata",
    },
    {
        "id": "ssgc",
        "title": "SSGC consumer complaint",
        "source_name": "Sui Southern Gas Company (SSGC)",
        "source_type": "utility_provider",
        "source_url": "https://www.ssgc.com.pk/",
        "category": "utility_bill_overcharging",
        "subcategory": "gas_bill_overcharging",
        "provider": "SSGC",
        "jurisdiction": "Sindh/Balochistan/service areas",
        "province": "Sindh",
        "city": None,
        "verified_at": "2026-06-14",
        "confidence_level": "official_source_metadata",
    },
    # ── WATER BILL OVERCHARGING ──────────────────────────────────────────────
    {
        "id": "wasa_lahore",
        "title": "WASA Lahore water complaint",
        "source_name": "Water and Sanitation Agency Lahore (WASA)",
        "source_type": "utility_provider",
        "source_url": "https://wasa.punjab.gov.pk/",
        "category": "utility_bill_overcharging",
        "subcategory": "water_bill_overcharging",
        "provider": "WASA",
        "jurisdiction": "Lahore",
        "province": "Punjab",
        "city": "Lahore",
        "verified_at": "2026-06-14",
        "confidence_level": "official_source_metadata",
    },
    {
        "id": "kwsb",
        "title": "KW&SB Karachi water complaint",
        "source_name": "Karachi Water and Sewerage Board (KW&SB)",
        "source_type": "utility_provider",
        "source_url": "https://www.kwsb.org.pk/",
        "category": "utility_bill_overcharging",
        "subcategory": "water_bill_overcharging",
        "provider": "KW&SB",
        "jurisdiction": "Karachi",
        "province": "Sindh",
        "city": "Karachi",
        "verified_at": "2026-06-14",
        "confidence_level": "official_source_metadata",
    },
    {
        "id": "wasa_faisalabad",
        "title": "WASA Faisalabad water complaint",
        "source_name": "Water and Sanitation Agency Faisalabad (WASA)",
        "source_type": "utility_provider",
        "source_url": "https://www.wasafaisalabad.gop.pk/",
        "category": "utility_bill_overcharging",
        "subcategory": "water_bill_overcharging",
        "provider": "WASA",
        "jurisdiction": "Faisalabad",
        "province": "Punjab",
        "city": "Faisalabad",
        "verified_at": "2026-06-14",
        "confidence_level": "official_source_metadata",
    },
    {
        "id": "wssp",
        "title": "WSSP Peshawar water complaint",
        "source_name": "Water and Sanitation Services Peshawar (WSSP)",
        "source_type": "utility_provider",
        "source_url": "https://wssp.gov.pk/",
        "category": "utility_bill_overcharging",
        "subcategory": "water_bill_overcharging",
        "provider": "WSSP",
        "jurisdiction": "Peshawar",
        "province": "Khyber Pakhtunkhwa",
        "city": "Peshawar",
        "verified_at": "2026-06-14",
        "confidence_level": "official_source_metadata",
    },
    # ── WORKPLACE HARASSMENT ─────────────────────────────────────────────────
    {
        "id": "fospah",
        "title": "FOSPAH workplace harassment complaint",
        "source_name": "Federal Ombudsperson Secretariat for Protection Against Harassment (FOSPAH)",
        "source_type": "federal_ombudsperson",
        "source_url": "https://www.fospah.gov.pk/",
        "category": "workplace_harassment_women",
        "subcategory": "workplace_harassment_women",
        "provider": None,
        "jurisdiction": "Pakistan (federal employees/organisations)",
        "province": None,
        "city": None,
        "verified_at": "2026-06-14",
        "confidence_level": "official_source_metadata",
    },
    {
        "id": "punjab_harassment_ombudsperson",
        "title": "Punjab Ombudsperson for Protection Against Harassment",
        "source_name": "Office of Ombudsperson — Punjab",
        "source_type": "provincial_ombudsperson",
        "source_url": "https://ombudsperson.punjab.gov.pk/",
        "category": "workplace_harassment_women",
        "subcategory": "workplace_harassment_women",
        "provider": None,
        "jurisdiction": "Punjab",
        "province": "Punjab",
        "city": None,
        "verified_at": "2026-06-14",
        "confidence_level": "official_source_metadata",
    },
    {
        "id": "sindh_harassment_ombudsperson",
        "title": "Sindh Ombudsperson for Protection Against Harassment",
        "source_name": "Office of Ombudsperson — Sindh",
        "source_type": "provincial_ombudsperson",
        "source_url": "https://www.sindhhombudsman.com.pk/",
        "category": "workplace_harassment_women",
        "subcategory": "workplace_harassment_women",
        "provider": None,
        "jurisdiction": "Sindh",
        "province": "Sindh",
        "city": None,
        "verified_at": "2026-06-14",
        "confidence_level": "official_source_metadata",
    },
    {
        "id": "kpk_harassment_ombudsperson",
        "title": "KPK Ombudsperson for Protection Against Harassment",
        "source_name": "Office of Ombudsperson — Khyber Pakhtunkhwa",
        "source_type": "provincial_ombudsperson",
        "source_url": "https://kpkombud.gov.pk/",
        "category": "workplace_harassment_women",
        "subcategory": "workplace_harassment_women",
        "provider": None,
        "jurisdiction": "Khyber Pakhtunkhwa",
        "province": "Khyber Pakhtunkhwa",
        "city": None,
        "verified_at": "2026-06-14",
        "confidence_level": "official_source_metadata",
    },
    {
        "id": "balochistan_harassment_ombudsperson",
        "title": "Balochistan Ombudsperson for Protection Against Harassment",
        "source_name": "Office of Ombudsperson — Balochistan",
        "source_type": "provincial_ombudsperson",
        "source_url": "https://balochistan.gov.pk/",
        "category": "workplace_harassment_women",
        "subcategory": "workplace_harassment_women",
        "provider": None,
        "jurisdiction": "Balochistan",
        "province": "Balochistan",
        "city": None,
        "verified_at": "2026-06-14",
        "confidence_level": "official_source_metadata",
    },
]
